# Generated by Django 2.1.5 on 2019-12-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrippersZone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpost',
            name='Olocation',
            field=models.CharField(default='boshundhora', max_length=225),
            preserve_default=False,
        ),
    ]
